const testModule = require('../templates/module-test'),
  image = require('../images/IS-QR'),
  benchmark = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAtCAYAAADcMyneAAAAAklEQVR4AewaftIAAAKGSURBVM3By29MYRjA4d/7ns/0Nr1MW5ditOnFpXTRiEqElcSSCEsJsZRY+AfsLZrYCxtdYidsJCISjSBITFRNm5ZKMNS0Y2Y6x/iwsOs52nFm+j2P2N9wmOI4xXGK4xTHKY5THKc4TnGc4jjFcYZVyuSW+JDNUyuGFcgt/eDaeJqH6U9kiz61ZPiHl3PzXLqXIpNbYi0YQrz7lufinZcU/DIIa0IJcXX8LQW/zFpSAsznSzyazrDWlABvPi/gAkOAbMFnpTY217O/u5PNrQ00xQxRMgQRQAjVsM7j3MHtHB7YhKdCNRgqFPOU0WN76euMU02GUJYgp0d66euMU21KBZJtTRwfSlILSgWGtybwVKgFQxhhWb2dzdSKoQJbWhpYiY+LRe68niOdyTHxKUu26LOcRGOM9oY6Rro7OLY7SaIxxl+GKrmdmuPK+CQFv8y/zOdLzOdLpL8scvPFLOcP7eTIji7+MFTB9SdTjD2dphKl8k9G76eI1xkO9KxHCSIWxIJYEAtiQSyIJUz6yyJjz6ZALIgFsSAWxIJYEAtiQSyIBbEgFsSCWBALYrn8IEW26KNE7MaLGaKQLfrcTr1Hidjj2QxReZNZQIlYrvSDqEx+XkBxWOb7EoYwwvKEYEKkFMcpjjOEsqyeJUqK4xSHtdavQwkjgAACCCCAEKqnPQ4CCCCAAAIIIIAAAggggAACCCCAAAIIJBrrUCLW29FMVIa3tKNE7OhgEk+F/+WpcHQwiRKxXRtaOTHUzf86NdzL5pZGDFVwZm8/C0WfuxNzrFbMU87uG+D4nm38YQgigFART4ULhwY53N/FrVczPP/wlYJfJoinQk8izkBHCyeHukm2NfHXL0aNt5iWSds9AAAAAElFTkSuQmCC',
  options = {
    x: '20',
    y: '15',
    w: '40',
    h: '45'
  };

testModule('crop', options, benchmark, image);